DROP DATABASE IF EXISTS luisjdev_auth_api;
CREATE DATABASE luisjdev_auth_api;

USE luisjdev_auth_api;

CREATE TABLE user (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FULL_NAME VARCHAR(255),
    USERNAME VARCHAR(255) UNIQUE,
    EMAIL VARCHAR(255) UNIQUE,
    PWD VARCHAR(255)
);

CREATE TABLE api (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    API_NAME VARCHAR(255),
    API_ID VARCHAR(255) UNIQUE
);

CREATE TABLE user_api (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_USER INT NOT NULL,
    ID_API INT NOT NULL,
    EXPIRATION_RATE VARCHAR(255) DEFAULT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE KEY (ID_USER, ID_API)
);

ALTER TABLE user_api ADD FOREIGN KEY (ID_USER) REFERENCES user(ID);
ALTER TABLE user_api ADD FOREIGN KEY (ID_API) REFERENCES api(ID);